#!/bin/bash
# tsc strips whitespace during the conversion, so we temporarily format with empty
# comments to represent whitespace, convert, and revert.
# Additionally uses prettier to format the code, ensuring git will only pick changed files.

# Replace newlines with comments to skip whitespace stripping when compiling.
find ./src -type f -name "*.ts" -exec sed -i -e 's/^$/\/\//g' {} \;

# Compile all typescript files.
tsc

# Revert src and strip comments from scripts.
find ./src -type f -name "*.ts" -exec sed -i -e 's/\/\/$//g' {} \;
find ./scripts -type f -name "*.js" -exec sed -i -e 's/\/\/$//g' {} \;

# Format output with prettier and add to git.
find ./scripts -type f -name "*.js" -exec npx prettier --write {} \; -exec git add {} \;

cd "$(dirname "$0")"

if ! python3 ./build_archives.py; then
    echo "Python build script failed."
    exit 1 
fi

if ! python3 ./update_readme.py; then
    echo "Python readme script failed."
    exit 1 
fi